### ISSUE TITLE
TODO: Add Code Format Standards - Prettier, Lint

### ISSUE THREAD

**Issue by Dnouv** [RocketChat/RC4Conferences#109]
Introduce new prettier, and lint standards for the project, and whenever the user pushes their commit, make sure they have already in compliance with the standards

**Comment by VipinDevelops** [comment]
Hey, @Dnouv  I would like to introduce a new standard for code formatting and linting in our project. We will be using Prettier and Lint to ensure consistent and clean code across the entire project.
Please assign this to me. 
Thank you!

**Comment by VipinDevelops** [comment]
To solve this issue

1. I will Start by adding the necessary dependencies such as Prettier and a linting library like ESLint to your project.
2. Set up the configuration files for both Prettier and the linting library.
3. Create a pre-commit hook using tools like Husky or pre-commit. This hook will run the Prettier and linting checks before allowing a commit.

**Comment by VipinDevelops** [comment]
![image](https://user-images.githubusercontent.com/99081689/215319386-34890d2a-4109-43f5-9792-cf5389c8a482.png)
have a look at the rules and properties I added

**Comment by VipinDevelops** [comment]
https://github.com/RocketChat/RC4Conferences/pull/111 
Have a look at changes i made here in this PR

**Comment by Dnouv** [comment]
Hey @VipinDevelops 

Thank you so much for your interest. I would suggest not starting working on this since you are already working on #66 once you figure out a solution for it, and we have your PR merged for it, only then you should take up this issue. This will cause other new coming contributors to lose issues to work on. I hope you understand this message.

Thanks!

**Comment by thapar-vansh** [comment]
Hey @Dnouv , if @VipinDevelops  is busy on some other issue I can take on this one . I have prior experience with prettier and ES Lint as well . Can you please describe the linting rules you wanna implement ? Thanks !
