### ISSUE TITLE
Error when trying to visit create event page after admin login.

### ISSUE THREAD

**Issue by sandeep-pani** [RocketChat/RC4Conferences#131]
The following produces the error:
Login as>Admin>Create 

Actual Behavior:
![image](https://user-images.githubusercontent.com/80412459/228080182-ef277c48-fae4-4728-88fa-2bd729462619.png)

Expected Behavior:
Display the create event page.

**Comment by Dnouv** [comment]
Hey @sandeep-pani 

I think you are using Gitpod; if so, please make port `3000` public, and it should work perfectly.

Thank you!

**Comment by sandeep-pani** [comment]
That worked. Thanks!
