### ISSUE TITLE
[NEW] Add a new form field

### ISSUE THREAD

**Issue by Dnouv** [RocketChat/RC4Conferences#52]
Add a new form input field labeled "Event Organizer logo" (named `icon-image-url`) inside the `EventBasicCreate` component. And update the respective state change and form submit functions to incorporate an additional field.

Thank you!

**Comment by r3yc0n1c** [comment]
Hi! I'd like to work on this.

**Comment by Dnouv** [comment]
Hey @r3yc0n1c 
Thanks for taking the issue; please try to set up the development environment, and then you can find the function component and have the required form field added.
[Here](https://api.eventyay.com/#events) is the schema of the Event, which you can take reference to.

If you run into any issues or have any doubts please feel free to DM in the [RocketChat](https://open.rocket.chat/direct/evan.shu) or comment here. 
Looking forward to your contributions. Thank you!

**Comment by r3yc0n1c** [comment]
Hi @Dnouv 
I'm facing some issues while setting it up on Gitpod. Please check the inbox where I've mentioned the issues in detail.

**Comment by vish-han** [comment]
Hi!! @Dnouv 
If this issue is still open , I would love to work on it...

**Comment by Dnouv** [comment]
Hey @vish-han 

Thank you for your interest. But @r3yc0n1c is already working on this issue. Please look out for any new issues that will be opening in this project.
