### ISSUE TITLE
[NEW] Backport updated Top Menu Bar

### ISSUE THREAD

**Issue by Dnouv** [RocketChat/RC4Conferences#73]
We need to backport this PR to RC4Conferences https://github.com/RocketChat/RC4Community/pull/193, which updates the UI and logic of the Top Menu Bar.

Thank you!

**Comment by Aashray446** [comment]
Hey, I am willing to work on this issue, Currently, I going through both repo, and trying to understand the logics and changes that need to be done. Can you assign the issue to me?

**Comment by Dnouv** [comment]
Hey @Aashray446 
Thanks for your interest. Before assigning this issue, please discuss your approach here, what changes we need to make in RC4Conferences, and if you find any conflicting components, what approach will you take to resolve it?

Once we have discussed the approach, it will make things easier for you to work on, and the community can also help if they understand better what you are trying to do. 

Thank you!

**Comment by Aashray446** [comment]
OK, thanks for the reply, I am on the way to coming up with something. I will explain my approach soon. 

Thank you

**Comment by Aashray446** [comment]
I went to the component codes of both menubar, there won't be any conflicts, those menus are completely isolated and there are only three components that required changes. Only the profile picture of the person is a little concerning, I need to figure the way out if there is any profile picture being stored and available to consume

My approach is simple, making a new component that will have the exact same component as in the Rocketchat community, and then replacing the new menubar with the old in Eventadmin

**Comment by Aashray446** [comment]
@Dnouv I have a good idea about how to approach it. It's just I don't know how detailed I need to describe the way of implementing it. Hope I got it right, I am open to your suggestions.

**Comment by Dnouv** [comment]
Sure, go ahead to start backporting it; just take care of this part of [code](https://github.com/RocketChat/RC4Conferences/blob/5efa903d04141be775fa851900a404e4a52ad8ab/app/components/conferences/EventAdmin.js#L63)

Thank you!

**Comment by Aashray446** [comment]
Ok sure, I will take care of that  :-)
Thank you

**Comment by Aashray446** [comment]
@Dnouv I have sent a pull request, I am open to your suggestions :-)

**Comment by Aashray446** [comment]
@Dnouv sir, I have a small doubt. As you mentioned, the "Click to Chat " button should be hidden when the user is not logged in. The dummy login button is setting the sessionStorage for the dummy user
![image](https://user-images.githubusercontent.com/69245931/212544141-37fd9dc1-1a0a-429a-8604-69eea6a94fb9.png)

But in the menubar, it's checking the Cookies to check whether the User is logged in or not 
![image](https://user-images.githubusercontent.com/69245931/212544203-24ab6fa4-b016-4214-a2ef-29f8df2e22ca.png)

Is that the reason, this button is not able to appear even after the login?
![image](https://user-images.githubusercontent.com/69245931/212544273-9e6fdd6f-dbc0-4cc9-a184-86affbf9d689.png)

**Comment by Dnouv** [comment]
Correct, please don't show the `kebab` (three-dot menu) icon. We don't have any use for it right now. 

As for how to check if a user is logged in or not, there is a cookie `hashmail`, which is added whenever a new user is signed in and removed when they log out; you can use this.
Thank you!

PS. Please feel free to address me as only `Dnouv` I will be more than happy if you do so.

**Comment by Aashray446** [comment]
@Dnouv thanks for the information. I have included the changes you mentioned and created a PR.

Thank you!   :-)

**Comment by Aashray446** [comment]
@Dnouv You can close this issue :smiley:
