### ISSUE TITLE
[TODO] Add Component to allow uploading images for the event

### ISSUE THREAD

**Issue by Dnouv** [RocketChat/RC4Conferences#98]
Create a component that allows the user to upload the Images. This component should be used for getting the user images for "Event Poster Image", "Event Organizer logo", and "Speakers picture".

![image](https://user-images.githubusercontent.com/61188295/215274686-905fd727-1e53-4a31-a61c-a7746eb1f8cf.png)

It should have an image crop feature so that it fits the UI for showing the Event Poster, or any other place the crop size should be passed as a prop to the component.

https://user-images.githubusercontent.com/61188295/215274973-00732994-ac0d-414f-b0a9-67805d8fd848.mp4

Please feel free to comment and ask questions, if any. Thank you!

**Comment by imf-ali** [comment]
Hey @Dnouv I would like to work on this issue, can you assign it to me?

**Comment by Dnouv** [comment]
Hey @imf-ali 

I appreciate your interest. However, before getting started, could you please explain to me how you plan to go around to solve this issue? This will definitely speed up the development (once you start coding) since you have already researched the issues you might need to solve.

Thank you!

**Comment by imf-ali** [comment]
Hey @Dnouv, I am thinking above the event name we can introduce two input component for both event header image and logo. Also for the crop image part may use react-cropper module or react-image-crop if thats okay with you, else we can also try making it making it from scratch using HTML canvas.

**Comment by Dnouv** [comment]
Ok, sounds good. What would the difficulty level be if we were to create the crop component from scratch?

**Comment by imf-ali** [comment]
If we create from scratch It's going to somewhat medium to hard. Should take over a week, cause I will need to do a bit more research on advanced HTML canvas.

**Comment by Dnouv** [comment]
My apologies for the delay, @imf-ali 

Let's use an already existing package instead of re-inventing the wheel. Please go ahead, and choose one that works best, and is actively maintained+lite in size (I would recommend using this site to compare  -> https://bundlephobia.com/).

Thank you!
